name: openclaw-research
region: nyc

workers:
  - name: openclaw
    dockerfile_path: /Dockerfile
    source_dir: /
    instance_count: 1
    instance_size_slug: apps-s-1vcpu-2gb
    git:
      branch: main
      repo_clone_url: https://github.com/Rogue-Iteration/openclaw-do-gradient.git
    envs:
      # ============================================================
      # REQUIRED
      # ============================================================
      - key: GRADIENT_API_KEY
        scope: RUN_TIME
        type: SECRET
      - key: OPENCLAW_GATEWAY_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_BOT_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: TELEGRAM_ALLOWED_IDS
        scope: RUN_TIME
        type: SECRET
      - key: STABLE_HOSTNAME
        scope: RUN_TIME
        value: openclaw-research

      # ============================================================
      # FEATURE FLAGS — console-only mode
      # ============================================================
      - key: ENABLE_NGROK
        scope: RUN_TIME
        value: "false"
      - key: TAILSCALE_ENABLE
        scope: RUN_TIME
        value: "false"
      - key: ENABLE_UI
        scope: RUN_TIME
        value: "false"
      - key: SSH_ENABLE
        scope: RUN_TIME
        value: "false"

      # ============================================================
      # RESEARCH SKILL — Gradient AI Knowledge Base + Spaces storage
      # ============================================================
      - key: DO_API_TOKEN
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_ACCESS_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_SECRET_KEY
        scope: RUN_TIME
        type: SECRET
      - key: DO_SPACES_ENDPOINT
        scope: RUN_TIME
        value: "https://nyc3.digitaloceanspaces.com"
      - key: DO_SPACES_BUCKET
        scope: RUN_TIME
        value: "openclaw-research"
      - key: GRADIENT_KB_UUID
        scope: RUN_TIME
        type: SECRET
